### ISSUE TITLE
default to tailwindcss@4

### ISSUE THREAD

**Issue by prabirshrestha** [onejs/one#474]
Would be great if it would default to tailwindcss v4.

```sh
pnpm add tailwindcss@4
pnpm add -D @tailwindcss/postcss
```

then update `postcss.config.js` with the following.

```javascript
export default {
  plugins: {
    '@tailwindcss/postcss': {},
    autoprefixer: {},
  },
}
```

update `app/base.css` with the following:

```css
@import "tailwindcss";

.test {
  background-color: red;
}
```
